blogs/backweb/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from backweb import views


urlpatterns = [
    # django自带登录注销
    # login_required
    # url(r'^login/', views.login, name='login'),
    # url(r'^logout/', views.logout, name='logout'),

    # 自己实现登录注册注销
    url(r'^my_register/', views.my_register, name='my_register'),
    url(r'^my_login/', views.my_login, name='my_login'),
    url(r'^my_logout/', views.my_logout, name='my_logout'),

    url(r'^index/', views.index, name='index'),
    url(r'^management/', views.management, name='management'),
    url(r'^daaman/', views.daaman, name='daaman'),
    url(r'^password/', views.password, name='password'),
    url(r'^conceal/(\d+)/', views.conceal, name='conceal'),
    url(r'^recommend/(\d+)/', views.recommend, name='recommend'),
    url(r'^delman/(\d+)/', views.delman, name='delman'),
    url(r'^updateman/(\d+)/', views.updateman, name='updateman'),

    url(r'^add_user', views.add_user, name='add_user'),
    url(r'^role_premission', views.role_premission, name='role_premission'),
    url(r'^user_role', views.user_role, name='user_role'),
    url(r'^list_user', views.list_user, name='list_user'),
]

blogs/job/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from job import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^front/', include('front.urls', namespace='front')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/backweb/models.py
from django.db import models


class Atype(models.Model):
    name = models.CharField(max_length=10)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'atype'


class Permission(models.Model):
    """
    权限表
    文章列表权限 -----> LISTARTICLE
    文章添加权限 -----> ADDARTICLE
    文章编辑权限 -----> EDILARTICLE
    文章删除权限 -----> DELARTICLE
    """
    p_name = models.CharField(max_length=15)

    class Meta:
        db_table = 'permission'


class Role(models.Model):
    """
    角色表
    """
    r_name = models.CharField(max_length=10, unique=True)
    # 每个角色可能有1个或多个权限
    r_p = models.ManyToManyField(Permission)

    class Meta:
        db_table = 'role'


class Article(models.Model):
    # 名字
    a_name = models.CharField(max_length=30, unique=True, null=False)
    # 类别
    a_category = models.ForeignKey(Atype, null=True)
    # 描述
    a_desc = models.CharField(max_length=50, null=True)
    # 内容
    a_content = models.TextField()
    # 是否隐藏
    a_conceal = models.BooleanField(default=False)
    # 是否推荐
    a_recommend = models.BooleanField(default=True)
    # 图片
    image_url = models.ImageField(upload_to='upload', null=True)
    # 点击量
    a_hit = models.IntegerField(default=0)
    # 创建时间
    create_time = models.DateTimeField(auto_now_add=True)

    # 数据库表名
    class Meta:
        db_table = 'article'


class User(models.Model):
    # 用户名
    username = models.CharField(max_length=10)
    # 密码
    password = models.CharField(max_length=255)
    # 是否超级用户
    is_superuser = models.BooleanField(default=False)
    # 注册时间
    create_time = models.DateTimeField(auto_now_add=True)
    # session的id
    session_id = models.CharField(max_length=30, null=True)
    # 过期时间
    out_time = models.DateTimeField(null=True)
    # 用户和角色是1对多关系
    u_r = models.ForeignKey(Role, null=True)

    class Meta:
        db_table = 'user'

blogs/backweb/views.py
from datetime import datetime, timedelta

from django.contrib import auth
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from backweb.models import Article, Atype, User, Role, Permission

import random


def login(request):
    if request.method == 'GET':
        return render(request, 'backweb/login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # 验证用户名和密码是否正确
        # 用auth_user数据库的匹配输入信息
        user = auth.authenticate(request,
                          username=username,
                          password=password)
        # 验证用户成功
        if user:
            # 登录
            auth.login(request, user)
            return HttpResponseRedirect(reverse('backweb:index'))
        else:
            return HttpResponseRedirect(reverse('backweb:login'))


def index(request):
    if request.method == 'GET':
        return render(request, 'backweb/index.html')


def logout(request):
    if request.method == 'GET':
        # 退出
        auth.logout(request)
        return HttpResponseRedirect(reverse('backweb:login'))


def management(request):
    if request.method == 'GET':
        # 使用切片实现分页
        # 第一种
        # page_num = request.GET.get('page', 1)
        # start_art = 1 * (int(page_num) - 1)
        # end_art = 1 * (int(page_num))
        # arts = Article.objects.all()[start_art: end_art]
        # 第二种
        # 如果没值就给page赋1
        judge = request.GET.get('judge', '')
        price = request.GET.get('price', '')
        if judge == 'a_name':
            articles = Article.objects.filter(Q(a_name__contains=price) | Q(a_content__contains=price))
        elif judge == 'id':
            articles = Article.objects.filter(id=price)
        else:
            articles = Article.objects.all()

        page_num = int(request.GET.get('page', 1))
        # Paginator给对象分页
        paginator = Paginator(articles, 5)
        arts = paginator.page(page_num)
        return render(request, 'backweb/management.html', {'arts': arts,
                                                           'judge': judge,
                                                           'price': price})
    if request.method == 'POST':
        judge = request.POST.get('judge')
        price = request.POST.get('price')
        if judge == 'a_name':
            articles = Article.objects.filter(a_name__contains=price)
        else:
            articles = Article.objects.filter(id=int(price))
        page_num = int(request.GET.get('page', 1))
        # Paginator给对象分页
        paginator = Paginator(articles, 5)
        arts = paginator.page(page_num)
        return render(request, 'backweb/management.html', {'arts': arts})


def daaman(request):
    if request.method == 'GET':
        types = Atype.objects.all()
        return render(request, 'backweb/daaman.html', {'types': types})
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        category = request.POST.get('category')
        content = request.POST.get('content')
        img = request.FILES.get('img')
        a_conceal = request.POST.get('a_conceal')
        a_recommend = request.POST.get('a_recommend')
        a_conceal = True if a_conceal == 'on' else False
        a_recommend = True if a_recommend == 'on' else False

        Article.objects.create(a_name=name,
                               a_desc=desc,
                               a_category_id=int(category),
                               a_content=content,
                               a_conceal=a_conceal,
                               a_recommend=a_recommend,
                               image_url=img)
        return HttpResponseRedirect(reverse('backweb:management'))


def password(request):
    if request.method == 'GET':
        return render(request, 'backweb/password.html')
    if request.method == 'POST':
        oldpassword = request.POST.get('oldpassword')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        session_id = request.COOKIES.get('session_id')
        user = User.objects.filter(session_id=session_id)
        if user[0].password != oldpassword:
            return render(request, 'backweb/password.html', {'error': '旧密码不正确'})
        if password1 != password2:
            return render(request, 'backweb/password.html', {'error': '两次密码不正确'})
        user.update(password=password2)
        return render(request, 'backweb/login.html', {'error': '密码修改成功，请重新登录'})


def conceal(request, id):
    if request.method == 'GET':
        arts = Article.objects.filter(id=id)
        flag = arts[0].a_conceal
        if flag:
            arts.update(a_conceal=False)
        else:
            arts.update(a_conceal=True)
        return HttpResponseRedirect(reverse('backweb:management'))


def recommend(request, id):
    if request.method == 'GET':
        arts = Article.objects.filter(id=id)
        flag = arts[0].a_recommend
        if flag:
            arts.update(a_recommend=False)
        else:
            arts.update(a_recommend=True)
        return HttpResponseRedirect(reverse('backweb:management'))


def delman(request, id):
    if request.method == 'GET':
        Article.objects.filter(id=id).delete()
        return HttpResponseRedirect(reverse('backweb:management'))


def updateman(request, id):
    if request.method == 'GET':
        artdd = Article.objects.get(id=id)
        types = Atype.objects.all()
        return render(request, 'backweb/updateman.html', {'artdd': artdd, 'types': types, 'id1': id})
    if request.method == 'POST':
        id = request.POST.get('id')
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        category = request.POST.get('category')
        content = request.POST.get('content')
        img = request.FILES.get('img')

        Article.objects.filter(id=id).update(a_name=name,
                                             a_desc=desc,
                                             a_category_id=category,
                                             a_content=content)
        if img:
            Article.objects.filter(id=id).update(image_url=img)
        return HttpResponseRedirect(reverse('backweb:management'))


def my_register(request):
    if request.method == 'GET':
        return render(request, 'backweb/register.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        # 先验证用户是否注册过
        user = User.objects.filter(username=username).exists()
        if user:
            error = '用户名已经存在，请直接登录'
            return render(request, 'backweb/register.html', {'error': error})
        else:
            # 两次密码正确
            if password1 == password2:
                User.objects.create(username=username, password=password1)
                return HttpResponseRedirect(reverse('backweb:my_login'))
            else:
                error = '两次密码不正确'
                return render(request, 'backweb/register.html', {'error': error})


def my_login(request):
    if request.method == 'GET':
        return render(request, 'backweb/login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.filter(username=username, password=password).first()
        if user:
            # 帐号密码正确
            # 第一步，给地址的cookie设值
            res = HttpResponseRedirect(reverse('backweb:index'))
            s = '1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM'
            session_id = ''
            for i in range(20):
                session_id += random.choice(s)
            out_time = datetime.now() + timedelta(days=1)
            res.set_cookie('session_id', session_id, expires=out_time)
            # 第二步，服务端存cookie中设的值
            user.session_id = session_id
            user.out_time = out_time
            user.save()
            # 返回地址
            return res
        else:
            error = '用户名或密码错误'
            return render(request, 'backweb/login.html', {'error': error})


def my_logout(request):
    if request.method == 'GET':
        # 1.删除服务端的session_id值
        user = request.user
        user.session_id = ''
        user.save()
        # 2.删除浏览器的session_id值
        res = HttpResponseRedirect(reverse('backweb:index'))
        res.delete_cookie('session_id')
        return res


def add_user(request):
    if request.method == 'GET':
        return render(request, 'backweb/add_user.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        user = User.objects.filter(username=username).exists()
        if user:
            error = '员工账号已存在'
            return render(request, 'backweb/add_user.html', {'error': error})
        if password1 == password2:
            User.objects.create(username=username, password=password1)
            # 创建用户成功返回用户列表
            return HttpResponseRedirect(reverse('backweb:list_user'))
        else:
            error = '两次输入密码不正确'
            return render(request, 'backweb/add_user.html', {'error': error})


def list_user(request):
    if request.method == 'GET':
        users = User.objects.all()
        return render(request, 'backweb/list_user.html', {'users': users})


def role_premission(request):
    if request.method == 'GET':
        # 角色列表,role.r_name
        roles = Role.objects.all()
        # 权限列表,pers.p_name
        pers = Permission.objects.all()
        return render(request, 'backweb/role_premission.html', {'pers': pers, 'roles': roles})
    if request.method == 'POST':

blogs/templates/backweb/add_user.html
{% extends 'backweb/base.html' %}

{% block content %}

<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">添加用户</h2>
      </div>
     <form action="" method="post" enctype="multipart/form-data">
         {%  csrf_token %}
     <section>
      <ul class="ulColumn2">
          {{ error }}
       <li>
        <span class="item_name" style="width:120px;">用户名：</span>
        <input name="username" value="" type="text" class="textbox textbox_295" placeholder="用户名..."/>
{#        <span class="errorTips">错误提示信息...</span>#}
       </li>
       <li>
        <span class="item_name" style="width:120px;">密码：</span>
        <input name="password1" value="" type="password" class="textbox textbox_295" placeholder="密码..."/>
{#        <span class="errorTips">错误提示信息...</span>#}
       </li>
          <li>
        <span class="item_name" style="width:120px;">确认密码：</span>
        <input name="password2" value="" type="password" class="textbox textbox_295" placeholder="确认密码..."/>
{#        <span class="errorTips">错误提示信息...</span>#}
       </li>
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <input type="submit" class="link_btn"/>
     </section>
     </form>
 </div>
</section>
{% endblock %}

blogs/templates/backweb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>后台管理系统</title>
        {% load static %}
    <meta name="author" content="DeathGhost" />
    <link rel="stylesheet" type="text/css" href="{% static 'backweb/css/style.css' %}">
    <!--[if lt IE 9]>
    <script src="{% static 'backweb/js/html5.js' %}"></script>
    <![endif]-->
    <script src="{% static 'backweb/js/jquery.js' %}"></script>
    <script src="{% static 'backweb/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script>

	(function($){
		$(window).load(function(){

			$("a[rel='load-content']").click(function(e){
				e.preventDefault();
				var url=$(this).attr("href");
				$.get(url,function(data){
					$(".content .mCSB_container").append(data); //load new content inside .mCSB_container
					//scroll-to appended content
					$(".content").mCustomScrollbar("scrollTo","h2:last");
				});
			});

			$(".content").delegate("a[href='top']","click",function(e){
				e.preventDefault();
				$(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
			});

		});
	})(jQuery);
    </script>
</head>
<body>
    <header>
         <h1><img src="/static/backweb/images/admin_logo.png"/></h1>
         <ul class="rt_nav">
          <li><a href="{% url 'front:index' %}" target="_blank" class="website_icon">站点首页</a></li>
          <li><a href="{% url 'backweb:my_logout' %}" class="quit_icon">安全退出</a></li>
         </ul>
    </header>
    <aside class="lt_aside_nav content mCustomScrollbar">
         <h2><a href="{% url 'backweb:index' %}">起始页</a></h2>
         <ul>
         {% if user.is_superuser %}
          <li>
           <dl>
            <dt>用户管理</dt>
            <dd><a href="{% url 'backweb:list_user' %}">用户列表</a></dd>
            <dd><a href="{% url 'backweb:add_user' %}">添加用户</a></dd>
            <dd><a href="{% url 'backweb:role_premission' %}">添加角色权限</a></dd>
            <dd><a href="{% url 'backweb:user_role' %}">用户角色管理</a></dd>
            <dd><a href="{% url 'backweb:password' %}">修改密码</a></dd>
           </dl>
          </li>
          {% endif %}
         {% if 'LISTARTICLE' in user.user_permission %}
          <li>
           <dl>
            <dt>文章相关</dt>
            <dd><a href="{% url 'backweb:management' %}">文章管理</a></dd>
           </dl>
          </li>
         {% endif %}
         </ul>
    </aside>
    {% block content %}
    {% endblock %}
</body>
</html>

blogs/templates/backweb/base2.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>
    {% block title %}
    {% endblock %}
</title>
<meta name="author" content="DeathGhost" />
<link rel="stylesheet" type="text/css" href="/static/backweb/css/style.css" />
<style>
body{height:100%;background:#16a085;overflow:hidden;}
canvas{z-index:-1;position:absolute;}
</style>
<script src="/static/backweb/js/jquery.js"></script>
            {% load static %}
<script src="{% static 'backweb/js/verificationNumbers.js' %}"></script>
<script src="/static/backweb/js/Particleground.js"></script>
<script>
$(document).ready(function() {
  //粒子背景特效
  $('body').particleground({
    dotColor: '#5cbdaa',
    lineColor: '#5cbdaa'
  });
  //验证码
  createCode();
  //测试提交，对接程序删除即可
  $(".submit_btn").click(function(){
	  location.href="index.html";
	  });
});
</script>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

blogs/templates/backweb/index.html
{% extends 'backweb/base.html' %}

blogs/templates/backweb/list_user.html
{% extends 'backweb/base.html' %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">用户列表</h2>
      </div>
      <table class="table">
       <tr>
        <th>编号</th>
        <th>用户名</th>
        <th>角色</th>
        <th>操作</th>
       </tr>
       {% for user in users %}
       <tr>
        <td class="center">{{ user.id }}</td>
        <td class="center">{{ user.username }}</td>
        <td class="center">{{ user.u_r.r_name }}</td>
        <td class="center">
         <a href="/web/about/{{ user.id }}" title="预览" class="link_icon" target="_blank">&#118;</a>
         <a href="/backweb/updateman/{{ user.id }}" title="编辑" class="link_icon">&#101;</a>
         <a href="/backweb/delman/{{ user.id }}" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
       {% endfor %}
      </table>
        <aside class="paging">
        {% if arts.has_previous %}
                <a href="{% url 'backweb:management' %}?page={{ arts.previous_page_number }}">上一页</a>
        {% endif %}
                <a href="{% url 'backweb:management' %}">第一页</a>
            {% for i in arts.paginator.page_range %}
                <a href="{% url 'backweb:management' %}?page={{ i }}">{{ i }}</a>
            {% endfor %}
                <a href="{% url 'backweb:management' %}?page={{ arts.paginator.num_pages }}">最后一页</a>
      {% if arts.has_next %}
                <a href="{% url 'backweb:management' %}?page={{ arts.next_page_number }}">下一页</a>
        {% endif %}
        </aside>
 </div>
</section>
{% endblock %}

blogs/templates/backweb/login.html
{% extends 'backweb/base2.html' %}

{% block title %}
    登录界面
{% endblock %}
{% block content %}
<dl class="admin_login">
 <dt>
  <strong>站点后台管理系统</strong>
  <em>Management System</em>
 </dt>
    <form action="" method="post">
        {% csrf_token %}
        {{ error }}
         <dd class="user_icon">
          <input type="text" placeholder="账号" name="username" class="login_txtbx"/>
         </dd>
         <dd class="pwd_icon">
          <input type="password" placeholder="密码" name="password" class="login_txtbx"/>
         </dd>
         <dd>
          <input type="submit" value="立即登录" class="submit_btn"/>
         </dd>
        <dd>
            <a href="{% url 'backweb:my_register' %}">没有账号？立即注册</a>
        </dd>
    </form>
 <dd>
  <p>© 2017-2018 wang 版权所有</p>
  <p>贵K2-20100821-1</p>
 </dd>
</dl>
{% endblock %}

blogs/templates/backweb/management.html
{% extends 'backweb/base.html' %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
{% if 'LISTARTICLE' in user.user_permission %}
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">文章列表</h2>
      {% if 'ADDARTICLE' in user.user_permission %}
       <a href="{% url 'backweb:daaman' %}" class="fr top_rt_btn add_icon">添加文章</a>
      {% endif %}
      </div>
        <script>
            function up() {
                var judge = $("#judge").val()
                var price = $("#price").val()
                location.href = '/backweb/management?judge=' + judge + '&price=' + price
            }
        </script>
      <section class="mtb">
       <select class="select" name="judge" id="judge">
        <option value="a_name">关键词</option>
        <option value="id">文章ID</option>
       </select>
       <input type="text" id="price" class="textbox textbox_225" placeholder="输入文章关键词或文章ID..." name="price"/>
       <input type="submit" value="查询" class="group_btn" onclick="up()"/>
      </section>
      <table class="table">
       <tr>
        <th>编号</th>
        <th>首图</th>
        <th>文章名称</th>
        <th>描述</th>
        <th>文章种类</th>
        <th>隐藏</th>
        <th>推荐</th>
        <th>字数</th>
        <th>点击量</th>
        <th>创建时间</th>
        <th>操作</th>
       </tr>
       {% for art in arts %}
       <tr>
        <td class="center">{{ art.id }}</td>
        <td class="center"><img src="/media/{{ art.image_url }}" width="50" height="50"></td>
        <td class="center">{{ art.a_name }}</td>
        <td class="center">{{ art.a_desc }}</td>
        <td class="center">{{ art.a_category.name }}</td>
       <td class="center">
        {% if art.a_conceal %}
           <a href="/backweb/conceal/{{ art.id }}" title="是" class="link_icon">&#89;</a>
        {% else %}
           <a href="/backweb/conceal/{{ art.id }}" title="否" class="link_icon">&#88;</a>
        {% endif %}
       </td>
       <td class="center">
        {% if art.a_recommend %}
           <a href="/backweb/recommend/{{ art.id }}" title="是" class="link_icon">&#89;</a>
        {% else %}
           <a href="/backweb/recommend/{{ art.id }}" title="否" class="link_icon">&#88;</a>
        {% endif %}
       </td>
        <td class="center">{{ art.a_content | length }}</td>
        <td class="center">{{ art.a_hit }}</td>
        <td class="center">{{ art.create_time|date:'Y-m-d h:m:s' }}</td>
        <td class="center">
        {% if 'EDILARTICLE' in user.user_permission %}
         <a href="/backweb/updateman/{{ art.id }}" title="编辑" class="link_icon">&#101;</a>
        {% endif %}
        {% if 'DELARTICLE' in user.user_permission %}
         <a href="/backweb/delman/{{ art.id }}" title="删除" class="link_icon">&#100;</a>
        {% endif %}
        </td>
       </tr>
       {% endfor %}
      </table>
        <aside class="paging">
        {% if arts.has_previous %}
                <a href="{% url 'backweb:management' %}?page={{ arts.previous_page_number }}&judge={{ judge }}&price={{ price }}">上一页</a>
        {% endif %}
                <a href="{% url 'backweb:management' %}?&judge={{ judge }}&price={{ price }}">首页</a>
            {% for i in arts.paginator.page_range %}
                <a href="{% url 'backweb:management' %}?page={{ i }}&judge={{ judge }}&price={{ price }}">{{ i }}</a>
            {% endfor %}
                <a href="{% url 'backweb:management' %}?page={{ arts.paginator.num_pages }}&judge={{ judge }}&price={{ price }}">尾页</a>
        {% if arts.has_next %}
                <a href="{% url 'backweb:management' %}?page={{ arts.next_page_number }}&judge={{ judge }}&price={{ price }}">下一页</a>
        {% endif %}
        </aside>
 </div>
{% endif %}
</section>
{% endblock %}

blogs/templates/backweb/password.html
{% extends 'backweb/base.html' %}

{% block content %}

<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">修改密码</h2>
      </div>
    <section>
    <form action="" method="POST">
        {% csrf_token %}
        <p>{{ error }}</p>
      <ul class="ulColumn2">
        <li>
        <span class="item_name" style="width:120px;">输入旧密码：</span>
        <input type="password" class="textbox textbox_295" placeholder="输入密码..." name="oldpassword">
        <br/>
        <br/>
        <br/>
        <span class="item_name" style="width:120px;">输入新密码：</span>
        <input type="password" class="textbox textbox_295" placeholder="输入密码..." name="password1">
        <br/>
        <br/>
        <br/>
        <span class="item_name" style="width:120px;">确认密码：</span>
        <input type="password" class="textbox textbox_295" placeholder="确认密码..." name="password2">
           <br/>
           <br/>
           <br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <input type="submit" value="提交" class="group_btn"/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <input type="reset" value="重置" class="group_btn"/>
       </li>
      </ul>
    </form>
     </section>
 </div>
</section>

{% endblock %}

blogs/templates/backweb/register.html
{% extends 'backweb/base2.html' %}

{% block title %}
    注册界面
{% endblock %}
{% block content %}
<dl class="admin_login">
 <dt>
  <strong>站点后台管理系统</strong>
  <em>Management System</em>
 </dt>
    <form action="" method="post">
        {% csrf_token %}
        {{ error }}
         <dd class="user_icon">
          <input type="text" placeholder="账号" name="username" class="login_txtbx"/>
         </dd>
         <dd class="pwd_icon">
          <input type="password" placeholder="密码" name="password1" class="login_txtbx"/>
         </dd>
        <dd class="pwd_icon">
          <input type="password" placeholder="确认密码" name="password2" class="login_txtbx"/>
         </dd>
         <dd>
          <input type="submit" value="立即注册" class="submit_btn"/>
         </dd>
        <dd>
            <a href="{% url 'backweb:my_login' %}">已有帐号？返回登录</a>
        </dd>
    </form>
 <dd>
  <p>© 2017-2018 wang 版权所有</p>
  <p>贵K2-20100821-1</p>
 </dd>
</dl>
{% endblock %}