blogs/front/urls.py
from django.conf.urls import url

from front import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^article/(\d+)/', views.article, name='article'),
    url(r'^about/', views.about, name='about'),
    url(r'^index2/', views.index2, name='index2'),
]

blogs/job/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from job import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^front/', include('front.urls', namespace='front')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/templates/web/about.html
{% extends 'web/base.html' %}

{% block content %}
  <main class="r_box">
     <div class="about">
      <p>杨青，女，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
     </div>
  </main>

{% endblock %}

blogs/templates/web/article.html
{% extends 'web/base.html' %}

{% block content %}
    <main>
    <div class="infosbox">
      <div class="newsview">
        <h3 class="news_title">{{ a.a_name }}</h3>
        <div class="bloginfo">
          <ul>
         <li class="timer">创建时间：{{ a.create_time | date:'Y-m-d' }}</li>
         <li class="view">{{ a.a_hit }}人已阅读</li>
         {% if a.image_url %}
         <li class="view"><img src="/media/{{ a.image_url }}"></li>
         {% endif %}
          </ul>
        </div>
        <br/>
        <div class="news_con">
            {% autoescape off %}
            {{ a.a_content }}
            {% endautoescape %}
        </div>
      </div>
    </div>
  </main>
{% endblock %}

blogs/templates/web/base.html
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>首页_王运超个人博客</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
<link href="{% static 'web/css/base.css' %}" rel="stylesheet">
<link href="{% static 'web/css/index.css' %}" rel="stylesheet">
<link href="{% static 'web/css/m.css' %}" rel="stylesheet">
<script src="{% static 'web/js/jquery.min.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'web/js/hc-sticky.js' %}"></script>
<script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">王运超个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'front:index' %}">网站首页</a></li>
      <li><a href="{% url 'front:about' %}">关于我</a></li>
    </ul>
  </nav>
</header>
<article>
  <aside class="l_box">
  <script>
      function up() {
          var keyboard = $("#keyboard").val()
          location.href = '/front/index?keyboard=' + keyboard
      }
  </script>
    <div class="search">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" onclick="up()" type="button">
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
        <form action="">
            <ul>
      {% for aty in atys %}
        <li><a href="{% url 'front:index2' %}?type={{ aty.id }}">{{ aty.name }}({{ aty.count }})</a></li>
      {% endfor %}
      </ul>
        </form>
    </div>
    <div class="tuijian">
      <h2>站长推荐</h2>
      <ul>
          {% for art in arts1 %}
            {% if art.a_recommend %}
              <li><a href="/front/article/{{ art.id }}">{{ art.a_name }}</a></li>
            {% endif %}
          {% endfor %}
      </ul>
    </div>
     <div class="tuijian">
      <h2>点击排行</h2>
      <ul>
          {% for art in artsd %}
           {% if forloop.counter < 11 %}
              <li><a title="第{{ forloop.counter }}名" href="/front/article/{{ art.id }}">{{ art.a_name }}&nbsp;&nbsp;&nbsp;热度：{{ art.a_hit }}</a></li>
            {% endif %}
          {% endfor %}
      </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我</h2>
      <ul>
        <img src="{% static 'web/images/wx.jpg' %}">
      </ul>
    </div>
  </aside>

    {% block content %}
    {% endblock %}

</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">王运超个人博客</a> <a href="/">黔ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

blogs/templates/web/index.html
{% extends 'web/base.html' %}

{% block content %}
  <main class="r_box">
    {% for art in arts2 %}
        <li>
            <h3><a href="/front/article/{{ art.id }}">{{ art.a_name }}</a></h3>
            <h4>类别：{{ art.a_category.name }}</h4>
            <h5>热度：{{ art.a_hit }}</h5>
            <p>
                {{ art.a_desc }}
            </p>
        </li>
    {% endfor %}
        <div class="pagelist">
            <a href="{% url 'front:index' %}?keyboard={{ keyboard }}" class="curPage">首页</a>

            {% if arts2.has_previous %}
            <a href="{% url 'front:index' %}?page={{ arts2.previous_page_number }}&keyboard={{ keyboard }}" class="allpage"><b>上一页</b></a>&nbsp;&nbsp;
            {% endif %}

            {% for i in arts2.paginator.page_range %}
              <a href="{% url 'front:index' %}?page={{ i }}&keyboard={{ keyboard }}">{{ i }}</a>
            {% endfor %}

            {% if arts2.has_next %}
                <a href="{% url 'front:index' %}?page={{ arts2.next_page_number }}&keyboard={{ keyboard }}" class="allpage"><b>下一页</b></a>
            {% endif %}

            <a href="{% url 'front:index' %}?page={{ arts2.paginator.num_pages }}&keyboard={{ keyboard }}" class="curPage">尾页</a>
        </div>
  </main>
{% endblock %}

blogs/templates/web/index2.html
{% extends 'web/base.html' %}

{% block content %}
  <main class="r_box">
      <h1>{{ atyd.name }}类</h1>
    {% for art in arts2 %}
        <li>
            <h3><a href="/front/article/{{ art.id }}">{{ art.a_name }}</a></h3>
            <h5>热度：{{ art.a_hit }}</h5>
            <p>{{ art.a_desc }}</p>
        </li>
    {% endfor %}
        <div class="pagelist">
            <a href="{% url 'front:index2' %}?type={{ atyd.id }}" class="curPage">首页</a>

            {% if arts2.has_previous %}
            <a href="{% url 'front:index2' %}?type={{ atyd.id }}&page={{ arts2.previous_page_number }}" class="allpage"><b>上一页</b></a>&nbsp;&nbsp;
            {% endif %}

            {% for i in arts2.paginator.page_range %}
              <a href="{% url 'front:index2' %}?type={{ atyd.id }}&page={{ i }}">{{ i }}</a>
            {% endfor %}

            {% if arts2.has_next %}
                <a href="{% url 'front:index2' %}?type={{ atyd.id }}&page={{ arts2.next_page_number }}" class="allpage"><b>下一页</b></a>
            {% endif %}

            <a href="{% url 'front:index2' %}?type={{ atyd.id }}&page={{ arts2.paginator.num_pages }}" class="curPage">尾页</a>
        </div>
  </main>
{% endblock %}